---
apiVersion: "v1"
kind: "Namespace"
metadata:
  name: "oracle"
---
apiVersion: "extensions/v1beta1"
kind: "Deployment"
metadata:
  name: "oracledb2"
  namespace: "oracle"
  labels:
    app: "oracledb2"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "oracledb2"
  template:
    metadata:
      labels:
        app: "oracledb2"
    spec:
      containers:
      - name: "oracledb"
        image: "eu.gcr.io/leafy-envelope-212213/oracledb:latest"
        ports:
            - containerPort: 1521
            - containerPort: 5500
        volumeMounts:
            - name: "oracledb2-store"
              mountPath: "/ORCL"
      volumes:
      - name: "oracledb2-store"
        persistentVolumeClaim:
          claimName: "oracledb2-store"
            path: "ORCL"
---
apiVersion: "v1"
kind: "PersistentVolume"
metadata:
  name: "oracledb2-store" 
  namespace: "oracle"
spec:
  storageClassName: faster
  capacity:
    storage: "100Gi" 
  accessModes:
    - "ReadWriteOnce"
  gcePersistentDisk: 
    fsType: "ext4" 
    pdName: "dev-disk"
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: faster
provisioner: kubernetes.io/gce-pd
parameters:
  type: pd-ssd    
---
apiVersion: v1
kind: "PersistentVolumeClaim"
metadata:
  name: "oracledb2-store"
  namespace: "oracle"
  labels:
    name: "oracledb2-store"
  annotations:
    volume.alpha.kubernetes.io/storage-class: default
spec:
  storageClassName: faster
  accessModes: [ReadWriteOnce]
  resources:
    requests:
      storage: 10Gi
---
apiVersion: "v1"
kind: "Service"
metadata:
  name: "oracledb2-service"
  namespace: "oracle"
  labels:
    app: "oracledb2"
spec:
  ports:
  - name: "1521-to-1521-tcp"
    protocol: "TCP"
    port: 1521
    targetPort: 1521
  - name: "5500-to-5500-tcp"
    protocol: "TCP"
    port: 5500
    targetPort: 5500
  selector:
    app: "oracledb2"
  type: "LoadBalancer"
  loadBalancerIP: ""
---
apiVersion: "autoscaling/v1"
kind: "HorizontalPodAutoscaler"
metadata:
  name: "oracledb2-hpa"
  namespace: "oracle"
  labels:
    app: "oracledb2"
spec:
  scaleTargetRef:
    kind: "Deployment"
    name: "oracledb2"
    apiVersion: "apps/v1beta1"
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80

      
