---
apiVersion: "v1"
kind: "Namespace"
metadata:
  name: "oracle"
---
apiVersion: "extensions/v1beta1"
kind: "Deployment"
metadata:
  name: "oracledb2"
  namespace: "oracle"
  labels:
    app: "oracledb2"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "oracledb2"
  template:
    metadata:
      labels:
        app: "oracledb2"
    spec:
      initContainers:
        - name: "chmod-er"
          image: "eu.gcr.io/leafy-envelope-212213/oracledb:latest"
          imagePullPolicy: IfNotPresent
          command:
            - "/bin/chown"
            - "-R"
            - "oracle:oracle" 
            - "/home/oracle"
          volumeMounts:
            - mountPath: "/ORCL"            
              name: "oracledb2-v" 
      containers:
        - name: "oracledb2"
          image: "eu.gcr.io/leafy-envelope-212213/oracledb:latest"
          ports:
            - containerPort: 1521
            - containerPort: 5500
          volumeMounts:
            - mountPath: "/ORCL"
              name: "oracledb2-v"
      volumes:
          - name: "oracledb2-v"
            persistentVolumeClaim:
              claimName: "gce-pd-pvc"        
---
kind: "StorageClass"
apiVersion: "storage.k8s.io/v1"
metadata:
  name: "faster"
  namespace: "oracle"
provisioner: "kubernetes.io/gce-pd"
parameters:
  type: "pd-ssd"
  zone: "europe-west1-b"
  fsType: "ext4"
---  
apiVersion: v1
kind: "PersistentVolumeClaim"
metadata:
  name: "gce-pd-pvc"
  namespace: "oracle"
  labels:
    name: "oracledb2"
  annotations:
    volume.alpha.kubernetes.io/storage-class: "faster"
spec:
  storageClassName: "faster"
  accessModes: [ReadWriteOnce]
  resources:
    requests:
      storage: "100Gi"
---
apiVersion: "v1"
kind: "Service"
metadata:
  name: "oracledb2-service"
  namespace: "oracle"
  labels:
    app: "oracledb2"
spec:
  ports:
  - name: "1521-to-1521-tcp"
    protocol: "TCP"
    port: 1521
    targetPort: 1521
  - name: "5500-to-5500-tcp"
    protocol: "TCP"
    port: 5500
    targetPort: 5500
  selector:
    app: "oracledb2"
  type: "LoadBalancer"
  loadBalancerIP: ""
---
apiVersion: "autoscaling/v1"
kind: "HorizontalPodAutoscaler"
metadata:
  name: "oracledb2-hpa"
  namespace: "oracle"
  labels:
    app: "oracledb2"
spec:
  scaleTargetRef:
    kind: "Deployment"
    name: "oracledb2"
    apiVersion: "apps/v1beta1"
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80

      
