---
apiVersion: "v1"
kind: "PersistentVolume"
metadata:
  name: "oracledb2-disk" 
  namespace: "oracle"
spec:
  storageClassName: faster
  capacity:
    storage: "100Gi" 
  accessModes:
    - "ReadWriteOnce"
  gcePersistentDisk: 
    fsType: "ext4" 
    pdName: "dev-disk"
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: faster
provisioner: kubernetes.io/gce-pd
parameters:
  type: pd-ssd    
---